name: "Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: web
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - uses: gacts/install-podman@v1
      - uses: hustcer/setup-nu@main
        with:
          version: "*"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        run: nu ./compile-all.nu

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
